import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}", // Note the addition of the `app` directory.
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-montserrat)", ...fontFamily.sans],
      },
      colors:{
        primary:"var(--primary)",
        'primary-50':"var(--primary-50)",
        'primary-100':"var(--primary-100)",
        'primary-200':"var(--primary-200)",
        'primary-300':"var(--primary-300)",
        'primary-400':"var(--primary-400)",
        'primary-500':"var(--primary-500)",
        'primary-600':"var(--primary-600)",
        'primary-700':"var(--primary-700)",
        'primary-800':"var(--primary-800)",
        'primary-900':"var(--primary-900)",
        secondary:"var(--secondary)",
        'secondary-50':"var(--secondary-50)",
        'secondary-100':"var(--secondary-100)",
        'secondary-200':"var(--secondary-200)",
        'secondary-300':"var(--secondary-300)",
        'secondary-400':"var(--secondary-400)",
        'secondary-500':"var(--secondary-500)",
        'secondary-600':"var(--secondary-600)",
        'secondary-700':"var(--secondary-700)",
        'secondary-800':"var(--secondary-800)",
        'secondary-900':"var(--secondary-900)",
        warning:"var(--warning)",
        'warning-50':"var(--warning-50)",
        'warning-100':"var(--warning-100)",
        'warning-200':"var(--warning-200)",
        'warning-300':"var(--warning-300)",
        'warning-400':"var(--warning-400)",
        'warning-500':"var(--warning-500)",
        'warning-600':"var(--warning-600)",
        'warning-700':"var(--warning-700)",
        'warning-800':"var(--warning-800)",
        'warning-900':"var(--warning-900)",
        success:"var(--success)",
        'success-50':"var(--success-50)",
        'success-100':"var(--success-100)",
        'success-200':"var(--success-200)",
        'success-300':"var(--success-300)",
        'success-400':"var(--success-400)",
        'success-500':"var(--success-500)",
        'success-600':"var(--success-600)",
        'success-700':"var(--success-700)",
        'success-800':"var(--success-800)",
        'success-900':"var(--success-900)",
        error:"var(--error)",
        'error-50':"var(--error-50)",
        'error-100':"var(--error-100)",
        'error-200':"var(--error-200)",
        'error-300':"var(--error-300)",
        'error-400':"var(--error-400)",
        'error-500':"var(--error-500)",
        'error-600':"var(--error-600)",
        'error-700':"var(--error-700)",
        'error-800':"var(--error-800)",
        'error-900':"var(--error-900)",
        greyscale:"var(--greyscale)",
        'greyscale-50':"var(--greyscale-50)",
        'greyscale-100':"var(--greyscale-100)",
        'greyscale-200':"var(--greyscale-200)",
        'greyscale-300':"var(--greyscale-300)",
        'greyscale-400':"var(--greyscale-400)",
        'greyscale-500':"var(--greyscale-500)",
        'greyscale-600':"var(--greyscale-600)",
        'greyscale-700':"var(--greyscale-700)",
        'greyscale-800':"var(--greyscale-800)",
        'greyscale-900':"var(--greyscale-900)",
        black:"var(--black)",
        white:"var(--white)",
        'white-alt':"var(--white-alt)"
      }, 
      backgroundImage:{
        'greyscale-gradient':'var(--greyscale-gradient)',
        'success-gradient':"linear-gradient(180deg, rgba(52, 121, 18, 0.5) -28.5%, rgba(0, 0, 0, 0) 95.56%);",

      }
    },
  },
  plugins: [],
};
export default config;
